/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { RunScriptResult, DeployContractExecutionResult } from "@alephium/cli";
import { NetworkId } from "@alephium/web3";
import {
  PhoenixBank,
  PhoenixBankInstance,
  PhoenixFactory,
  PhoenixFactoryInstance,
  USDToken,
  USDTokenInstance,
} from ".";
import { default as testnetDeployments } from "../.deployments.testnet.json";

export type Deployments = {
  deployerAddress: string;
  contracts: {
    PhoenixBank: DeployContractExecutionResult<PhoenixBankInstance>;
    PhoenixFactory: DeployContractExecutionResult<PhoenixFactoryInstance>;
    USDToken: DeployContractExecutionResult<USDTokenInstance>;
  };
};

function toDeployments(json: any): Deployments {
  const contracts = {
    PhoenixBank: {
      ...json.contracts["PhoenixBank"],
      contractInstance: PhoenixBank.at(
        json.contracts["PhoenixBank"].contractInstance.address
      ),
    },
    PhoenixFactory: {
      ...json.contracts["PhoenixFactory"],
      contractInstance: PhoenixFactory.at(
        json.contracts["PhoenixFactory"].contractInstance.address
      ),
    },
    USDToken: {
      ...json.contracts["USDToken"],
      contractInstance: USDToken.at(
        json.contracts["USDToken"].contractInstance.address
      ),
    },
  };
  return {
    ...json,
    contracts: contracts as Deployments["contracts"],
  };
}

export function loadDeployments(
  networkId: NetworkId,
  deployerAddress?: string
): Deployments {
  const deployments =
    networkId === "testnet"
      ? testnetDeployments
      : undefined;
  if (deployments === undefined) {
    throw Error("The contract has not been deployed to the " + networkId);
  }
  const allDeployments = Array.isArray(deployments)
    ? deployments
    : [deployments];
  if (deployerAddress === undefined) {
    if (allDeployments.length > 1) {
      throw Error(
        "The contract has been deployed multiple times on " +
          networkId +
          ", please specify the deployer address"
      );
    } else {
      return toDeployments(allDeployments[0]);
    }
  }
  const result = allDeployments.find(
    (d) => d.deployerAddress === deployerAddress
  );
  if (result === undefined) {
    throw Error("The contract deployment result does not exist");
  }
  return toDeployments(result);
}
