/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as USDTokenContractJson } from "../tokens/USDToken.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace USDTokenTypes {
  export type Fields = {
    symbol: HexString;
    name: HexString;
    decimals: bigint;
    supply: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<USDTokenInstance, USDTokenTypes.Fields> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as USDTokenTypes.Fields;
  }

  at(address: string): USDTokenInstance {
    return new USDTokenInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<TestContractParams<USDTokenTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getSymbol", params);
    },
    getName: async (
      params: Omit<TestContractParams<USDTokenTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getName", params);
    },
    getDecimals: async (
      params: Omit<TestContractParams<USDTokenTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: Omit<TestContractParams<USDTokenTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getTotalSupply", params);
    },
    withdraw: async (
      params: TestContractParams<USDTokenTypes.Fields, { amount: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdraw", params);
    },
  };
}

// Use this object to test and deploy the contract
export const USDToken = new Factory(
  Contract.fromJson(
    USDTokenContractJson,
    "",
    "69324141d38ba40b9a9b64a650372b9c26b5db5b05e50b33b13447776c1ac587"
  )
);

// Use this class to interact with the blockchain
export class USDTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<USDTokenTypes.State> {
    return fetchContractState(USDToken, this);
  }

  methods = {
    getSymbol: async (
      params?: USDTokenTypes.CallMethodParams<"getSymbol">
    ): Promise<USDTokenTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        USDToken,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: USDTokenTypes.CallMethodParams<"getName">
    ): Promise<USDTokenTypes.CallMethodResult<"getName">> => {
      return callMethod(
        USDToken,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: USDTokenTypes.CallMethodParams<"getDecimals">
    ): Promise<USDTokenTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        USDToken,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: USDTokenTypes.CallMethodParams<"getTotalSupply">
    ): Promise<USDTokenTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        USDToken,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends USDTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<USDTokenTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      USDToken,
      this,
      calls,
      getContractByCodeHash
    )) as USDTokenTypes.MultiCallResults<Calls>;
  }
}
